#!/usr/bin/env bash
# ============================================
# Pull ANAMNESIS-Secrets from AWS and write .env
# ============================================
# Requires: aws CLI, jq, authenticated AWS SSO session
# Usage: ./pull_env.sh [profile_number]
#   profile_number: 1 = personal, 2 = work (default: 1)
# ============================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRET_NAME="ANAMNESIS-Secrets"
PROFILE="${1:-1}"
ENV_FILE="${SCRIPT_DIR}/.env"

# Determine AWS profile name
if [[ "$PROFILE" == "1" ]]; then
    PROFILE_NAME="personal"
elif [[ "$PROFILE" == "2" ]]; then
    PROFILE_NAME="work"
else
    PROFILE_NAME="$PROFILE"
fi

echo "Pulling ${SECRET_NAME} (profile: ${PROFILE_NAME})..."

# Fetch secret JSON
SECRET_JSON=$(aws secretsmanager get-secret-value \
    --secret-id "$SECRET_NAME" \
    --profile "$PROFILE_NAME" \
    --query SecretString \
    --output text 2>/dev/null)

if [[ -z "$SECRET_JSON" ]]; then
    echo "ERROR: Failed to pull secret. Check AWS SSO auth." >&2
    exit 1
fi

# Write .env file
{
    echo "# Auto-generated by pull_env.sh — do not commit"
    echo "# Source: AWS Secrets Manager / ${SECRET_NAME}"
    echo "# Generated: $(date -Iseconds)"
    echo ""
    echo "$SECRET_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"'
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo "Wrote $(wc -l < "$ENV_FILE") lines to ${ENV_FILE}"
echo "Done."
